export const DATE_FORMAT = "YYYY-MM-DD";

export const DAY_OF_WEEK_FORMAT_STATISTIC = "dd";
export const DAY_FORMAT_STATISTIC = "DD";

export const MAX_TITLE_LENGTH = 40;
export const MAX_DESCRIPTION_LENGTH = 1000;
export const MAX_KNOWLEDGE_COMMENT_LENGTH = 20000;
export const MAX_LINK_LENGTH = 1000;
export const MAX_IMG_LENGTH = 100000;

export enum CardAction {
    ADD, DELETE, CHANGE
}

export enum TypeOfTimer {
    LOOP, LONG_BREAK, SHORT_BREAK, WORK
}

export enum TypeOfCycle {
    LONG_BREAK, SHORT_BREAK, WORK, NONE
}

export enum ActionTypes {
    PRIORITY_TASK_CHANGE = "PRIORITY_TASK_CHANGE",
    RESET_CARDS_REQUEST = "RESET_CARDS_REQUEST",
    CHANGE_CARDS_REQUEST = "CHANGE_CARDS_REQUEST",
    DELETE_CARDS_REQUEST = "DELETE_CARDS_REQUEST",
    DELETE_GROUPS_FROM_CARDS_REQUEST = "DELETE_ALL_CARDS_REQUEST",
    ADD_CARDS_GROUP_REQUEST = "ADD_CARDS_GROUP_REQUEST",
    SET_CARDS_GROUP_REQUEST = "SET_CARDS_GROUP_REQUEST",
    CHANGE_CARDS_GROUP_REQUEST = "CHANGE_CARDS_GROUP_REQUEST",
    DELETE_CARDS_GROUP_REQUEST = "DELETE_CARDS_GROUP_REQUEST",
    ADD_CARDS_REQUEST = "ADD_CARDS_REQUEST",
    CONTINUE_TASK_TIMER_REQUEST = "CONTINUE_TASK_TIMER_REQUEST",
    RESULT_TASK_TIMER_REQUEST = "RESULT_TASK_TIMER_REQUEST",
    ADD_TASKS_REQUEST = "SET_TASKS_REQUEST",
    CREATE_BACKUP_REQUEST = "CREATE_BACKUP_REQUEST",
    GET_BACKUP_REQUEST = "GET_BACKUP_REQUEST",
    DELETE_BACKUP_REQUEST = "DELETE_BACKUP_REQUEST",
    LOAD_BACKUP_REQUEST = "LOAD_BACKUP_REQUEST",
    LOAD_SOURCES_FROM_LOCAL_STORAGE_REQUEST = "LOAD_SOURCES_FROM_LOCAL_STORAGE_REQUEST",
    UPDATE_BACKUP_REQUEST = "UPDATE_BACKUP_REQUEST",
    COMPLETE_TASK_REQUEST = "COMPLETE_TASK_REQUEST",
    CLOSE_TASK_REQUEST = "CLOSE_TASK_REQUEST",
    UNCOMPLETE_TASK_REQUEST = "UNCOMPLETE_TASK_REQUEST",
    START_TOMATO_TIMER = "START_TOMATO_TIMER",
    STOP_TOMATO_TIMER = "STOP_TOMATO_TIMER",
    PAUSE_TOMATO_TIMER = "PAUSE_TOMATO_TIMER",
    PROGRESS_TOMATO_TIMER = "PROGRESS_TOMATO_TIMER",
    DELETE_TASK_REQUEST = "DELETE_TASK_REQUEST",
    CHANGE_FILTER_REQUEST = "CHANGE_FILTER_REQUEST",
    REMOVE_FILTER_REQUEST = "REMOVE_FILTER_REQUEST",
    MAKE_KNOWLEDGE_READ_REQUEST = "MAKE_KNOWLEDGE_READ_REQUEST",
    CHANGE_DANGEROUS_LEVEL_REQUEST = "CHANGE_DANGEROUS_LEVEL_REQUEST",
    START_TASK_TIMER_REQUEST = "START_TASK_TIMER_REQUEST",
    STOP_TASK_TIMER_REQUEST = "STOP_TASK_TIMER_REQUEST",
    SET_KNOWLEDGE_REQUEST = "SET_KNOWLEDGE_REQUEST",
    REMOVE_KNOWLEDGE_REQUEST = "REMOVE_KNOWLEDGE_REQUEST",
    CHANGE_KNOWLEDGE_REQUEST = "CHANGE_KNOWLEDGE_REQUEST",
    LOAD_STORE_FROM_STORAGE_REQUEST = "LOAD_STORE_FROM_STORAGE",
    REMOVE_ERROR_REQUEST = "REMOVE_ERROR_REQUEST",
    SET_ERROR_REQUEST = "SET_ERROR_REQUEST",
    START_LOADING_REQUEST = "START_LOADING_REQUEST",
    STOP_LOADING_REQUEST = "STOP_LOADING_REQUEST",
    ADD_CURRENT_DATE_SETTINGS = "ADD_CURRENT_DATE_SETTINGS",
    ADD_COMMENT = "ADD_COMMENT",

    UPDATE_BALANCE_WHEEL_REQUEST = "ADD_CATEGORIES_REQUEST",
    ADD_TASK_IDS_IN_CATEGORIES_REQUEST = "ADD_TASK_IDS_IN_CATEGORIES_REQUEST",
}

export const APP_STORAGE_KEY = "APP_STORAGE_KEY";

export const BACKUP_FILE_NAME = "my-day.json";
export const BACKUP_FOLDER_NAME = "MyDayBackups";

export const DAY_IN_MILLIS = 86400000;

export const WEEK_DAY_INDEX = {
    MONDAY: 1,
    TUESDAY: 2,
    WEDNESDAY: 3,
    THURSDAY: 4,
    FRIDAY: 5,
    SATURDAY: 6,
    SUNDAY: 0,
    DEFAULT: -1
};

export const RANGE_OF_KNOWLEDGE = {
    MORE_FAMILIAR_CARD: 2,
    LOW_FAMILIAR_CARD: 1,
    NOT_FAMILIAR_CARD: 0
};

export const STACK_NAVIGATION_ROUTES_NAMES = {
    NEW_CARD_GROUP_SCREEN: "Новая группа",
    CARDS_SCREEN: "Карточки",
    REPEATER_SCREEN: "Повторение"
}
